### ISSUE TITLE
OpenEMS documentation

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#15]
Hello, I noticed in the last image of https://github.com/thomaslepoix/Qucs-RFlayout/blob/dev/doc/tutorials/openems.md
that the S11 of the measured filter becomes positive which is clearly not physical. Perhaps there was an issue with the vna cal?

**Comment by thomaslepoix** [comment]
As mentioned below, the measure range is only 1-3GHz, not 0-5GHz like the simulations one. These positive parts are how Qucs deal with it.
