### ISSUE TITLE
Autocoalesce close meshes?

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#16]
You highlight a very tedious problem with meshing in the openEMS tutorial. In particular, when you are simulating a stepped impedance or even an interdigital filter, the mesh lines can come very close to overlapping which causes the simulation time to skyrocket. Do you think it would be possible to include a feature where you can specify that these types of mesh lines should not be created, or averaged into one line? It might not work well for all cases but I think you could cover a good portion of them with such a simple fix. It would make higher order filter design much more convenient. Great work so far, this is a really nice tool!

**Comment by thomaslepoix** [comment]
Hi! thank you! :)

The mesh is precisely the difficult thing with OpenEMS. The best solution would be an automatic mesher of course. Without that, I chose to keep control (resolution, line by line control) in user hands that is to say in Octave land.

The OpenEMS function `SmoothMesh` I use has its own magic (case like "why a mesh resolution divisor of 80 produces a good result and 85 produces a totally broken one with 'divisions by 0' errors, etc. ?") so mesh optimisations criteras are quite unclear and/or random.

Averaging close lines could be a solution (I think I could try that and see), but I fear solutions that works in some cases only.

I spotted [this new project](https://github.com/matthuszagh/pyems), it is an abstraction layer to make OpenEMS user friendly. I have not tested it yet but it seems to embed an automatic mesher. I consider to move in future produced scripts from Octave to Python/pyems.
