### ISSUE TITLE
Scientific notation does not support "E" only "e"

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#18]
If you have a component where for example, length = 8.207329E-04, you get a warning when creating the .m file and the export fails. If you have length = 8.207329**e**-04 it works.

WARNING : Variable not found in component MS15 : 8.207329E-04 -> Assigned to 0. Try to start a simulation.

**Comment by thomaslepoix** [comment]
If Qucs supports it, Qucs-RFlayout must. The fix should be trivial.
