### ISSUE TITLE
Make --no-dump --no-nf2ff default

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#21]
I think it would make sense to make turn these options off by default. In my experience, the first thing you look at when designing a filter is the s-params. If there is something fishy in the parameters you look at the fields to see if you are exciting modes that you dont want. nf2ff is especially niche as it would likely be done last in the design process. Though perhaps for an antenna design it could be relevant right off the bat. Either way, I like having to explicitly enable more processing only when I need it as opposed to turning it off when I don't need it. May be a matter of personal preference. Thoughts?

**Comment by thomaslepoix** [comment]
Yes it makes sense, I agree with you.
