### ISSUE TITLE
disable silkscreen value being displayed in kicad export

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#22]
I noticed that the silkscreen values of the individual MLINs are visible in the default kicad export. I think it would be better if these had Visible: False by default. Normally the filter is expected to be a complete construct and not a coalition of individual elements. Debugging after the board is printed is difficult / impossible anyway depending on the frequency.

**Comment by thomaslepoix** [comment]
Is this really relevant since it is just one click on the side bar to enable / disable it?

Also if you want your circuit as one element, you may prefer exporting to a footprint (`.kicad_mod`).

I don't understand why this would make debug difficult.

**Comment by dom11990** [comment]
The silkscreen doesnt make it difficult, it is inherently difficult since it is a printed structure. I was just thinking that normally silkscreen is used to aid in debugging by providing part references or other text. In this case it wouldn't help though. I will try the other export type, maybe I mixed them up, I thought this was the footprint.

**Comment by thomaslepoix** [comment]
Oh I didn't get it! disable microstrip components silkscreen and not the whole board silkscreen. You are right these texts are useless once the board is printed. Good idea.

However, if you are designing a board on kicad, I would recommend you to export your filter as a footprint and to create a schematic component "filter" to associate with.
