### ISSUE TITLE
microstrip taper support

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#25]
Qucs 20 has a taper line, will this also be supported?

**Comment by thomaslepoix** [comment]
Is it this one?

![image](https://user-images.githubusercontent.com/26417323/95108136-27f89700-073b-11eb-9f3a-9da9d9437958.png)

If it is, it cannot. It looks like a microstrip but it is not, both extremities are impedances instead of widths and it is independant of substrate component.

**Comment by dom11990** [comment]
A taper is definitely a microstrip component, though I'd have to look at the source to see what they did. It should not be independent of substrate. Perhaps they don't actually have a microstrip model for it, only an "ideal" one?

**Comment by thomaslepoix** [comment]
Yes that's it, an ideal microstrip component.. What a strange thing
