### ISSUE TITLE
macOS instructions

### ISSUE THREAD

**Issue by fred-corp** [thomaslepoix/Qucs-RFlayout#37]
I was able to install on macOS with the following commands :

## Install dependencies with homebrew

```sh
brew install imagemagick
brew install qt
brew install --cask font-lato
brew install texlive
```

> Note : I may have had some dependencies preinstalled on my computer from other software installations/compilations, if someone can test this on their Mac it would be great, to see if there's something missing.

## Build from source

```sh
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build
sudo cmake --build build --target install
```

It may be useful to add those instructions to README.md :)

Tested on MacBook Pro 15" 2017 (Intel), macOS Sequoia (with OCLP)

**Comment by thomaslepoix** [comment]
Good news, thank you!
