### ISSUE TITLE
write_touchstone undefined in octave

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#7]
It appears that the write_touchstone function is not included. Does it come from another library?

>> write_touchstone('s', freq, spara, [name, port_suffix, '.s2p'])
error: 'write_touchstone' undefined near line 1 column 1

**Comment by thomaslepoix** [comment]
`write_touchstone()` is a part of CTB, install it and be sure it is accessible from your octave path.

Take a look here : https://github.com/thliebig/openEMS-Project
