### ISSUE TITLE
Mesh lines not respecting 1/3 rule

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#8]
The meshing does not seem to respect the 1/3 rule. For one the y mesh lines seem to be very close to the edge of the MLIN, and the x lines do 1/3 copper on one side of the MLIN and 2/3 copper on the other.

at a Via
![image](https://user-images.githubusercontent.com/4545056/86331686-b398ee00-bc49-11ea-9116-b6a27cfcec08.png)

at a Tee
![image](https://user-images.githubusercontent.com/4545056/86331735-c6abbe00-bc49-11ea-920b-0212e4485afa.png)

The same schematic from #6 was used for the generation.

I also get warnings of division by zero:

warning: division by zero
warning: called from
    SmoothMeshLines2>SmoothRange at line 301 column 5
    SmoothMeshLines2 at line 92 column 26
    AutoSmoothMeshLines at line 92 column 18
    SmoothMesh at line 54 column 12
    openems2 at line 225 column 6
warning: division by zero
warning: called from
    SmoothMeshLines2>SmoothRange at line 301 column 5
    SmoothMeshLines2 at line 92 column 26
    AutoSmoothMeshLines at line 92 column 18
    SmoothMesh at line 54 column 12
    openems2 at line 225 column 6
warning: division by zero
warning: called from
    SmoothMeshLines2>SmoothRange at line 301 column 5
    SmoothMeshLines2 at line 92 column 26
    AutoSmoothMeshLines at line 92 column 18
    SmoothMesh at line 54 column 12
    openems2 at line 225 column 6
warning: division by zero
warning: called from
    SmoothMeshLines2>SmoothRange at line 301 column 5
    SmoothMeshLines2 at line 92 column 26
    AutoSmoothMeshLines at line 92 column 18
    SmoothMesh at line 54 column 12
    openems2 at line 225 column 6
warning: division by zero
warning: called from
    SmoothMeshLines2>SmoothRange at line 301 column 5
    SmoothMeshLines2 at line 92 column 26
    AutoSmoothMeshLines at line 92 column 18
    SmoothMesh at line 54 column 12
    openems2 at line 225 column 6
warning: division by zero
warning: called from
    SmoothMeshLines2>SmoothRange at line 301 column 5
    SmoothMeshLines2 at line 92 column 26
    AutoSmoothMeshLines at line 92 column 18
    SmoothMesh at line 54 column 12
    openems2 at line 225 column 6

**Comment by thomaslepoix** [comment]
There is no way to totally automate the mesh generation, it is still to the user to ensure the mesh is correct.

So here we go! If you run the script with `--no-smoothmesh --no-process --no-postprocess`, you will see that the default mesh resolution is way too large. You can reduce it by growing its divisor `metal_div` in the script, or rerunning qucsrflayout with `--oems-metalres-div`. 200 seems to be fine.

![openems_60](https://user-images.githubusercontent.com/26417323/86423967-87c94700-bce1-11ea-9ab3-59a875255d9a.png)
![openems_200](https://user-images.githubusercontent.com/26417323/86423983-931c7280-bce1-11ea-8e2f-824be1151bdf.png)
![openems_200sm](https://user-images.githubusercontent.com/26417323/86423988-99125380-bce1-11ea-8b11-a3d686cf243f.png)

Warnings come from the OpenEMS `SmoothMesh()` function if some manually placed lines are too close.

Note that if some components produce really close lines, you might have to remove some manually by commenting lines in the script. Component names are commented for each line so they are not so painful to find. (It is not the case here)

I will write some tutorials ASAP :)

**Comment by thomaslepoix** [comment]
As I see you uses a via, do you think something about that #9 ?

**Comment by dom11990** [comment]
I added my thoughts on #9 . Yes some tutorials would be very helpful :) I would love to see a more graphical approach to configuring the different options. Perhaps even configuring the mesh in the export GUI as well as other settings such as the convergence criterion, mesh density, port offsets, active ports, frequencies for the far-field calcualtion, etc. Thoughts?

**Comment by thomaslepoix** [comment]
It is becoming quite stable but the OpenEMS feature is still under heavy development, so for now the GUI does not allow yet everything that the CLI does. But it should and it will.

About the script interface, it is a little more tricky as OpenEMS has its own workflow and I don't want and/or cannot distort it too much. However a kind of graphical runner could be good and feasible.
