### ISSUE TITLE
Vias implementation

### ISSUE THREAD

**Issue by thomaslepoix** [thomaslepoix/Qucs-RFlayout#9]
I implemented vias as centered on the adjacent component edge rather than edge to edge but I am not sure this is right.

![openems_via](https://user-images.githubusercontent.com/26417323/86424704-8862dd00-bce3-11ea-875c-16535f90d3cb.png)
![openems_novia](https://user-images.githubusercontent.com/26417323/86424719-8e58be00-bce3-11ea-877b-1efa1695822b.png)

I would need the opinion of regulars of RF design. Thank you in advance!

**Comment by dom11990** [comment]
Yeah this is rather tricky. From a designer perspective, I would prefer that the via is centered on the edge of the microstrip. However, I think the qucs model puts it on the end. So if you optimize the circuit prior to doing the oems simulation you will have deviations. I will post a question to them to see if they can answer what their model creates.

**Comment by thomaslepoix** [comment]
So the answer came from the version 3 of QucsStudio from whom comes the MVIA model :

![image](https://user-images.githubusercontent.com/26417323/95687866-9b504c00-0c06-11eb-9440-9352c65ef2b1.png)
